version: '3'
services:
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      # MYSQL_DATABASE: llmtask
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      # - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
  #PHP Service
  app:
    build:
      context: .
      dockerfile: DockerFile
    image: php:alpine
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      DB_HOST: db
      TESTING_DB_HOST: db
    working_dir: /var/www
    volumes:
      # - ./src:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
# #Docker Networks
networks:
  app-network:
    driver: bridge
# #Volumes
# volumes:
#   dbdata:
#     driver: local